### ISSUE TITLE
BOM ?

### ISSUE THREAD

**Issue by nathmo** [concretedog/stoRPer#1]
Hi, I'm really interested in your mecanum wheel for a totally unrelated project (Kerbal space program Navball replica) and I would like to know if the BOM is somewhere that I missed or if the mecanum are custom-made to find the file :)

It's a really nice project, by the way :)

**Comment by feiltom** [comment]
hello, same thing. have you a BOM ?
i see your project on hack a day. very interested for children in  a educational fablab.
Cdt

**Comment by concretedog** [comment]
Hi all, thanks for your interest... It's been a busy week! I need to write up a minimal BOM. I guess it's a little variable as you can do different things with the design. I'll add a BOM document to the repo or add details on the readme but for now... You'll need;

The PCB
Some N20 metal gear motors in a gear ratio of your choice rated up to 6V. 
Some 3D printed motor mount clips to attach the motors (files in the 3D models section)
8* 6mm M2 bolts and nuts to attach motor mounts. 
A raspberry pi Pico or Pico W, or equivalent footprint microcontroller board.
Some N20 compatible wheels (either commercial or home brew/3D printed)
Some kind of power supply (simplest is a small USB pack, other options are a 14500 or 18650 cell wired into the power input)
Semi optional, an upper deck to attach power supply too. 

But as I say, that's just a guide, you could use different items or design to the basic PCB/chassis in different ways.

**Comment by concretedog** [comment]
> Hi, I'm really interested in your mecanum wheel for a totally unrelated project (Kerbal space program Navball replica) and I would like to know if the BOM is somewhere that I missed or if the mecanum are custom-made to find the file :)
> 
> It's a really nice project, by the way :)

Thanks for the kind words. Regarding the Mecanum wheels, they are a commercial item. They are available in lots of places in the UK I bought mine via Pimoroni https://shop.pimoroni.com/products/mecanum-wheels-pack-of-4?variant=31590632063059 

I'm sure there are mecanum wheel designs out there for 3D print and assembly as well! Might be worth searching around.

**Comment by concretedog** [comment]
Marking this as closed as I've added a brief BOM to the readme.
